kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 36680
  apiServerAddress: 0.0.0.0
nodes:
  # the control plane node
  - role: control-plane
    image: kindest/node:v1.19.11
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        controlPlaneEndpoint: host.docker.internal:36680
        apiServer:
          certSANs:
            - host.docker.internal
          extraArgs:
            max-requests-inflight: "1000"
            max-mutating-requests-inflight: "500"
            default-watch-cache-size: "500"