# permissions for end users to view containermanagementobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containermanagementobject-viewer-role
rules:
- apiGroups:
  - containership.app
  resources:
  - containermanagementobjects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - containership.app
  resources:
  - containermanagementobjects/status
  verbs:
  - get
