# permissions for end users to edit gates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gate-editor-role
rules:
- apiGroups:
  - containership.app
  resources:
  - gates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - containership.app
  resources:
  - gates/status
  verbs:
  - get
