# permissions for end users to view gates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gate-viewer-role
rules:
- apiGroups:
  - containership.app
  resources:
  - gates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - containership.app
  resources:
  - gates/status
  verbs:
  - get
