# permissions for end users to view registriesconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registriesconfig-viewer-role
rules:
- apiGroups:
  - containership.app
  resources:
  - registriesconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - containership.app
  resources:
  - registriesconfigs/status
  verbs:
  - get
