// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureContainerRegistries) DeepCopyInto(out *AzureContainerRegistries) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureContainerRegistries.
func (in *AzureContainerRegistries) DeepCopy() *AzureContainerRegistries {
	if in == nil {
		return nil
	}
	out := new(AzureContainerRegistries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerManagementObject) DeepCopyInto(out *ContainerManagementObject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerManagementObject.
func (in *ContainerManagementObject) DeepCopy() *ContainerManagementObject {
	if in == nil {
		return nil
	}
	out := new(ContainerManagementObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerManagementObject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerManagementObjectList) DeepCopyInto(out *ContainerManagementObjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerManagementObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerManagementObjectList.
func (in *ContainerManagementObjectList) DeepCopy() *ContainerManagementObjectList {
	if in == nil {
		return nil
	}
	out := new(ContainerManagementObjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerManagementObjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerManagementObjectSpec) DeepCopyInto(out *ContainerManagementObjectSpec) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make([]Image, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerManagementObjectSpec.
func (in *ContainerManagementObjectSpec) DeepCopy() *ContainerManagementObjectSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerManagementObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerManagementObjectStatus) DeepCopyInto(out *ContainerManagementObjectStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerManagementObjectStatus.
func (in *ContainerManagementObjectStatus) DeepCopy() *ContainerManagementObjectStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerManagementObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Destinations) DeepCopyInto(out *Destinations) {
	*out = *in
	if in.AzureContainerRegistries != nil {
		in, out := &in.AzureContainerRegistries, &out.AzureContainerRegistries
		*out = make([]AzureContainerRegistries, len(*in))
		copy(*out, *in)
	}
	if in.GoogleContainerRegistry != nil {
		in, out := &in.GoogleContainerRegistry, &out.GoogleContainerRegistry
		*out = make([]GoogleContainerRegistries, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Destinations.
func (in *Destinations) DeepCopy() *Destinations {
	if in == nil {
		return nil
	}
	out := new(Destinations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleContainerRegistries) DeepCopyInto(out *GoogleContainerRegistries) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleContainerRegistries.
func (in *GoogleContainerRegistries) DeepCopy() *GoogleContainerRegistries {
	if in == nil {
		return nil
	}
	out := new(GoogleContainerRegistries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
	if in.SupportedTags != nil {
		in, out := &in.SupportedTags, &out.SupportedTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Destinations.DeepCopyInto(&out.Destinations)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}
