name: Go Release

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        id: changelog
        uses: ./changelog
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.5.0
        with:
          version: latest
          args: release --rm-dist --release-notes=${{ steps.changelog.outputs.filepath }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}