name: Release

on:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          
      - name: Generate Release Notes
        id: changelog
        uses: ./.github/changelog
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.5.0
        with:
          version: latest
          args: release --rm-dist --release-notes=${{ steps.changelog.outputs.filepath }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Release Deployment YAML file
        run: make release
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          
      # Get release information to determine id of the current release
      - name: Get Release
        id: get-release-info
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload deployment YAML file to GitHub release
      - name: Upload Deployment YAML file
        id: upload-deployment-yaml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/relativitydev/containership/releases/${{ steps.get-release-info.outputs.id }}/assets?name=containership-${{ steps.get_version.outputs.VERSION }}.yaml
          asset_path: containership-${{ steps.get_version.outputs.VERSION }}.yaml
          asset_name: containership-${{ steps.get_version.outputs.VERSION }}.yaml
          asset_content_type: application/x-yaml
          
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: relativitydev/containership:latest,relativitydev/containership:${{ steps.previoustag.outputs.tag }}